server:
  #端口号
  port: 8991
  #项目名，如果不设定，默认是 /
#  servlet:
#    context-path: /vote
  
  
 # redis配置，以下有默认配置的也可以使用默认配置配置采用Redis一主三从的的配置方式来提高缓存的吞吐量
redis:
# Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  pool:
  # 连接池最大连接数（使用负值表示没有限制）
    max-active: 8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: 1
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 0
    # 连接超时时间（毫秒）
  timeout: 0
  
  
#spring:
#  application:
#      name: spring-boot-redis
#  redis:
#      host: 192.168.145.132
#      port: 6379
#      timeout: 20000
#      cluster:
#          nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
#         maxRedirects: 6
#    pool:
#       max-active: 8
#      min-idle: 0
#     max-idle: 8
#    max-wait: -1
          
#哨兵模式
#redis.sentinel.host1=192.168.177.128
#redis.sentinel.port1=26379

