   
server:
  #端口号
  port: 80
  #项目名，如果不设定，默认是 /
 # context-path: /vote
  
logging:
  #日志存储地址
  file: "E:/logs/config/demo.log"
 #  level:
 #   sun: warn
 #   orgSpringframework: info
 #   root: debug
info:
  name: "入门案例"

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.shcd.vote.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.winter.model  # 注意：对应实体类的路径
#  configLocation: classpath:mybatis-config.xml


#开发配置
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/test
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: mysqlRoot
    driver-class-name: com.mysql.cj.jdbc.Driver
 # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp   
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    